import fs from 'node:fs'
import react from '@vitejs/plugin-react'
import { defineConfig, loadEnv } from 'vite'

// Inline the self-hosted @font-face rules (public/fonts/fonts.css, generated by
// scripts/fetch-fonts.mjs from the exact Google Fonts URL the Webflow export used) into <head>:
// no render-blocking third-party stylesheet, same font binaries (byte-identical), no glyph shift.
function inlineFonts() {
  return {
    name: 'foreshift:inline-fonts',
    transformIndexHtml(html) {
      const css = fs.readFileSync(new URL('./public/fonts/fonts.css', import.meta.url), 'utf8').trim()
      return html.replace('<!--fonts-->', `<style>${css}</style>`)
    },
  }
}


// Serve /api/contact during `npm run dev` with the same handler Vercel runs in production, so the
// form works locally. Secrets come from .env.local (server-side only, never bundled).
function devApi(mode) {
  return {
    name: 'foreshift:dev-api',
    configureServer(server) {
      for (const [k, v] of Object.entries(loadEnv(mode, process.cwd(), ''))) process.env[k] ??= v
      server.middlewares.use('/api/contact', async (req, res) => {
        const { default: handler } = await server.ssrLoadModule('/api/contact.js')
        await handler(req, res)
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => ({
  plugins: [react(), inlineFonts(), devApi(mode)],
  build: {
    // manifest is consumed (then deleted) by scripts/prerender.mjs for the modulepreload list.
    manifest: true,
    sourcemap: false,
  },
}))
